import type { ImageStyle } from './types';

export const STYLES: ImageStyle[] = [
  { id: 'anime', name: 'ZOMBIE', prompt: 'Transform the uploaded human portrait into a realistic zombie version. Keep the original pose, facial structure, and lighting, but make the skin pale, decayed, and bruised. Add subtle rotting flesh textures, dark greenish tones, blood splatters, hollow eyes, visible teeth or bone in places, and torn clothing. The background should be dark, eerie, cinematic lighting — as if from a horror movie or post-apocalyptic scene. Ultra-detailed, realistic style, 8K resolution, high quality, dramatic lighting.' },
  { id: 'cartoon', name: 'Witch', prompt: 'Transform the uploaded human portrait into a witch version. Keep the person’s facial features and expression, but add mystical elements: dark magical aura, glowing eyes, enchanted tattoos, flowing robes, a pointed witch hat, silver jewelry, and ancient spell symbols in the background. Include details like swirling mist, candlelight reflections, floating runes, and a faint green or purple glow. Style: dark fantasy, ultra-detailed, cinematic lighting, highly realistic, 8K quality.' },
  { id: 'realistic', name: 'WereWolf', prompt: 'Transform the uploaded human portrait into a werewolf version. Keep the person’s facial structure recognizable, but add realistic wolf-like features: glowing yellow eyes, sharp fangs, fur growing from face and arms, wolf ears, and clawed hands. Depict a transformation under the full moon, with mist, forest shadows, and a dark cinematic atmosphere. Style: hyper-realistic, dark fantasy, detailed fur texture, 8K resolution, dramatic lighting.' },
  { id: 'cyberpunk', name: 'Vampire', prompt: 'Transform the uploaded human portrait into a vampire version. Keep the person’s face recognizable but add elegant, dark vampire traits: pale skin, glowing red eyes, sharp fangs, and a mysterious expression. Include gothic clothing, dark velvet cape, blood-red lighting, and a moody atmosphere with candles, mist, and a full moon glow. Style: hyper-realistic, gothic horror, cinematic lighting, 8K detail, ultra sharp focus.' },
  { id: 'fantasy', name: 'MUMMY', prompt: 'Transform the uploaded human portrait into an ancient Egyptian mummy version. Keep the person’s facial structure recognizable, but wrap parts of the face and body with aged linen bandages. Add cracked dry skin, glowing eyes, golden Egyptian amulets, and ancient hieroglyphs in the background. Include dust, desert light, and mystical energy emerging from the mummy’s eyes. Style: hyper-realistic, cinematic, dark ancient fantasy, 8K ultra detailed.' },
  { id: 'oil_painting', name: 'GHOST', prompt: 'Transform the uploaded human portrait into a ghostly version. Keep the person’s facial features slightly visible through a semi-transparent, ethereal form. Add a soft glowing aura, misty trails, and a faint, floating appearance. Surround with fog, flickering lights, and a dark or abandoned background (such as an old house, forest, or graveyard). Style: cinematic, supernatural, hyper-realistic, soft lighting, 8K ultra detailed.' },
  { id: 'pixel_art', name: 'Pumpkin Head', prompt: 'Transform the uploaded human portrait into a pumpkin head version. Replace the person’s head with a carved jack-o’-lantern pumpkin, glowing from the inside with orange firelight. Keep the body, pose, and outfit of the person the same. Add Halloween atmosphere: fog, autumn leaves, moonlight, and a dark background. Style: cinematic, spooky fantasy, ultra-detailed, 8K, realistic lighting.' },
   { id: 'Skeleton', name: 'Skeleton', prompt: 'Transform the uploaded human portrait into a skeleton version. Replace the person’s face and visible skin with realistic bone structure — skull, rib cage, and skeletal hands — while keeping the person’s pose, clothes, and overall composition intact. Maintain anatomical accuracy but preserve human proportions. Add a spooky and cinematic atmosphere with fog, dim blue lighting, and shadows. Style: ultra-detailed, photorealistic, 8K, Halloween fantasy aesthetic.' },
];

export const MAX_HISTORY_ITEMS = 3;
